[package]
name = "just"
version = "1.24.0"
authors = ["Casey Rodarmor <casey@rodarmor.com>"]
autotests = false
categories = ["command-line-utilities", "development-tools"]
description = "🤖 Just a command runner"
edition = "2021"
exclude = ["/book", "/icon.png", "/screenshot.png", "/www"]
homepage = "https://github.com/casey/just"
keywords = ["command-line", "task", "runner", "development", "utility"]
license = "CC0-1.0"
readme = "crates-io-readme.md"
repository = "https://github.com/casey/just"
rust-version = "1.63"

[workspace]
members = [".", "bin/ref-type", "bin/generate-book", "bin/update-contributors"]

[dependencies]
ansi_term = "0.12.1"
blake3 = { version = "1.5.0", features = ["rayon", "mmap"] }
camino = "1.1.6"
clap = { version = "4.5.1", features = ["wrap_help", "cargo"] }
clap_complete = "4.5.1"
ctrlc = { version = "3.4.2", features = ["termination"] }
derivative = "2.0.0"
dirs = "5.0.1"
dotenvy = "0.15.7"
edit-distance = "2.0.0"
env_logger = "0.11.2"
heck = "0.4.1"
lexiclean = "0.0.1"
libc = "0.2.153"
log = "0.4.20"
num_cpus = "1.16.0"
regex = "1.10.3"
semver = "1.0.22"
serde = { version = "1.0.197", features = ["derive", "rc"] }
serde_json = "1.0.114"
sha2 = "0.10.8"
similar = { version = "2.4.0", features = ["unicode"] }
snafu = "0.8.0"
strum = { version = "0.26.1", features = ["derive"] }
target = "2.0.0"
tempfile = "3.10.0"
typed-arena = "2.0.2"
unicode-width = "0.1.11"
uuid = { version = "1.7.0", features = ["v4"] }

[dev-dependencies]
cradle = "0.2.2"
executable-path = "1.0.0"
pretty_assertions = "1.4.0"
temptree = "0.2.0"
which = "6.0.0"
yaml-rust = "0.4.5"

[lib]
doctest = false

[[bin]]
path = "src/main.rs"
name = "just"
test = false

[features]
# No features are active by default.
default = []
# The `help4help2man` feature modifies the message produced by `--help`
# so that `help2man` produces a reasonable man page.
help4help2man = []

# The public documentation is minimal and doesn't change between
# platforms, so we only build them for linux on docs.rs to save
# their build machines some cycles.
[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[profile.release]
lto = true
codegen-units = 1
strip = true

[[test]]
name = "integration"
path = "tests/lib.rs"
